/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AttractionCursor: typeof import('./src/components/feature/AttractionCursor.vue')['default']
    CircleCursor: typeof import('./src/components/feature/CircleCursor.vue')['default']
    CursorCanvas: typeof import('./src/components/feature/CursorCanvas.vue')['default']
    FluidCursor: typeof import('./src/components/feature/FluidCursor.vue')['default']
    GuitarStrings: typeof import('./src/components/feature/GuitarStrings.vue')['default']
    LoadingScreen: typeof import('./src/components/LoadingScreen.vue')['default']
    MagicBall: typeof import('./src/components/MagicBall.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    OilFluidCursor: typeof import('./src/components/feature/OilFluidCursor.vue')['default']
    ParticleBackground: typeof import('./src/components/feature/ParticleBackground.vue')['default']
    PreFooter: typeof import('./src/components/PreFooter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RouteTransition: typeof import('./src/components/RouteTransition.vue')['default']
    WorkGallery: typeof import('./src/components/feature/WorkGallery.vue')['default']
  }
}
